### ISSUE TITLE
prowgen multiple targets

### ISSUE THREAD

**Issue by mjudeikis** [openshift/ci-operator-prowgen#79]
Our jobs depends on multiple targets. 
In example running job `X` it requires multiple targets to be ran for it:
```
    name: pull-ci-openshift-openshift-azure-master-e2e-upgrade-v1.2
    rerun_command: /test e2e-upgrade-v1.2
    spec:
      containers:
      - args:
        - --artifact-dir=$(ARTIFACTS)
        - --give-pr-author-access-to-namespace=true
        - --target=[images]
        - --target=[output:stable:azure-controllers]
        - --target=[output:stable:etcdbackup]
        - --target=[output:stable:metricsbridge]
        - --target=[output:stable:sync]
        - --target=rbac
        - --target=e2e-upgrade-v1.2
```

In this case `e2e-upgrade-v1.2` requires all `images` to be available, and template `rbac` to be available too. But prowgen when generating step for:
```
- artifact_dir: /tmp/artifacts
  as: e2e-upgrade-v1.2
  commands: ARTIFACT_DIR=/tmp/artifacts SOURCE=v1.2 make upgrade
  secret: 
    name: azure
    mount_path: /usr/secrets
  container:
    from: src
```

Does not allow to all additional targets :/
